---
title: "Time Series Analyisis"
runningheader: "Term Paper" # only for pdf output
subtitle: "An implementation in R Markdown" # only for html output
author: "Daniel Bustillo Mac Lean"
date: 31-08-2021
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex

link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

# Motivation

Increasing evidence has shown that human emissions of carbon dioxide and
other greenhouse gases are a primary driver of climate change (IPCC,
2013). This makes worldwide emissions one of the world's most pressing
challenges and has provoked various international agreement, like the
Paris Agreement on emission reduction and other climate goals. Three of
the largest current emitting regions are China, the US and the EU.

# Introduction

The main topic of this term paper is to analyze and model the trends of
CO2 emissions in some of the countries of the European Union, the United
States of America and China (and perhaps comparing them with emerging
economics such as Brazil and India). Current actions to mitigate the
climate effects of such steep rise of CO2 emissions over the last 50-60
years (citation needed) are not enough to reach the goals set in the
Paris Agreement by 2030. Such is the slowed response from the governing
institutions and international organizations that the current trends
indicate that the temperature increases (and all the consequences behind
it) will be irreversible in less that 5 years(citation needed). This
paper will analyze the trends of CO2 emissions of the above-mentioned
countries and will design a fitting econometric model. Lastly, a
forecast for the next periods based on the model will be presented.


-   What do we already know about the subject (literature review)? Use
    citations: @lingenfelser2011systematic shows that... Alternative
    Forms of the Wald test are considered [@kuncheva2004combining].

Some exploratory data analysis on the different datasets

What kind of data do we use? C02 emissions per capita, why? Arguments
for using that measure -\> Although all 3 regions are really big, the
population density is different and thus "spreading" the CO2 emissions
by population gives us more sensible data and accounted for the
different sizes of population.
Maybe disaggregate countries in the EU (high income vs low income), same in the USA with big states (California, Texas) vs poorer states such as (Mississippi, Alabama, Arkansas in Continental USA ). Kind of panel data, is there data available for that?

Plot of CO2 in Europe

Plot of CO2 in USA

Plot of CO2 in China

(Plot of CO2 in Brazil

Plot of CO2 in India)

The econometric and economic theory is briefly described and related
literature is presented

Idea: compare with GDP or GNP

Include kyoto and paris agreement and other historical events
(fukushima, fridays for future?)

# The model and data

The econometric model and the data applied are described, a first
descriptive analysis of the data is shown

-   Describe the data and its quality.All data is taken from the World
    Bank's Database, overall this database has proven to be reliable for industrialized countries, not su much for developing countries, since their data might be manipulated(?).
    

-   How was the data sample selected?

    As stated in the Introduction, our interest here is to analyze the
    trends of the 3 biggest emitters of Co2 in the world: the USA, the
    European Union and China [quote on that]. Additionally, we compare
    those trends and forecast, with trends and forecast of emerging
    economies such as Brazil and India, as those countries display worrying trends on CO2 emissions that could lead to irreversible temperature rises, contamination and deforestation.
    

-   Provide descriptive statistics such as:

    -   time period,

    -   item number of observations, data frequency,

    -   item mean, median,

    -   item min, max, standard deviation,

    -   item skewness, kurtosis, Jarque--Bera statistic,

    -   item time series plots, histogram.
    

-   Allows the reader to judge whether the sample is biased or to
    evaluate possible impacts of outliers, for example.

-   Here tables can be easily integrated using the `kable()` function in
    the `knitr` package (with perhaps some additional help from the
    `kableExtra` package). `kable()` will automatically generate a label
    for the table environment. That way you don't have to manually enter
    in the table in LaTex, you can embed tables from R code.

    
# Methodology

-   How was the data analyzed ?

-   Present the underlying economic model/theory and give reasons why it
    is suitable to answer the given problem[^1].

-   Present econometric/statistical estimation method and give reasons
    why it is suitable to answer the given problem.

-   Allows the reader to judge the validity of the study and its
    findings.

-   Depending on the topic this section can also be split up into
    separate sections.

# Estimation and results

The model choice is reasoned well in statistical and economic terms, the
estimation results are presented, the results are interpreted and
connected to the economic theory and literature from point 1.

Find an appropriate ARIMA model to describe the three series. Base your
decision on (P)ACFs, unit root tests, AIC and further diagnostic checks.
What limits the validity of these results? 4. Forecast the CO2 emissions
one period ahead and for 2030 based on the chosen model. Evaluate the
forecast in comparison to an alternative prediction method. 5. Discuss
the economic consequences of your results and suggest different
techniques how your model and a potential long-term forecast could be
improved.


-   Do the results support or do they contradict economic theory ?

-   What does the reader learn from the results?

-   Try to give an intuition for your results.

-   Provide robustness checks.

-   Compare to previous research.

# Conclusion:

Summary of the main results and outlook on further interesting research
directions


-   Give a short summary of what has been done and what has been found.

-   Expose results concisely.

-   Draw conclusions about the problem studied. What are the
    implications of your findings?

-   Point out some limitations of study (assist reader in judging
    validity of findings).

-   Suggest issues for future research.


[^1]: Here is an example of a footnote.





-   R Markdown can also supports math equations just like *LaTeX*!

    -   *Equation* \@ref(eq:SpecDens) *represents the ACs of a
        stationary stochastic process:* \begin{equation}
                f_y(\lambda) = (2\pi)^{-1} \sum_{j=-\infty}^{\infty}
                               \gamma_j e^{-i\lambda j}
                             =(2\pi)^{-1}\left(\gamma_0 + 2 \sum_{j=1}^{\infty}
            \gamma_j \cos(\lambda j)\right)
                                           (\#eq:SpecDens)
        \end{equation} *where* $i=\sqrt{-1}$ is the imaginary unit,
        $\lambda \in [-\pi, \pi]$ is the frequency and the $\gamma_j$
        are the autocovariances of $y_t$.

    -   Equations can be referenced with `\@ref(eq:<name>)`, where name
        is defined by adding `(\#eq:<name>)` in the line immediately
        before `\end{equation}`.




# References


@article{owidco2andothergreenhousegasemissions,
    author = {Hannah Ritchie and Max Roser},
    title = {CO₂ and Greenhouse Gas Emissions},
    journal = {Our World in Data},
    year = {2020},
    note = {https://ourworldindata.org/co2-and-other-greenhouse-gas-emissions}
}
